### ISSUE TITLE
mute download KB logs

### ISSUE THREAD

**Issue by baranowb** [jboss-set/cryo#6]
When CRYO is handling logs, it would be good to purge download entries - possibly push those into another log file?
Entries like: 
INFO [CRYO][**00:05:33:34:642**]: 5613/6922 KB
INFO [CRYO][**00:05:33:35:860**]: 5617/6922 KB
INFO [CRYO][**00:05:33:35:860**]: 5621/6922 KB
INFO [CRYO][**00:05:33:35:860**]: 5625/6922 KB
INFO [CRYO][**00:05:33:35:860**]: 5629/6922 KB

or

NFO [CRYO][**00:05:35:35:745**]: Downloading: https://xxxx.Final.pom
INFO [CRYO][**00:05:35:38:646**]: 4/4 KB
INFO [CRYO][**00:05:35:40:360**]:
INFO [CRYO][**00:05:35:40:360**]: Downloaded: https://xxxxx.Final.pom (4 KB at 0.7 KB/sec)
 Those are part of maven build/download cycles, in case of CRYO those are not relevant unless it fails to download, which in turn would lead to job failure.

**Comment by sudeshnas93** [comment]
Hello @baranowb, can I take up this issue? Also, it would be helpful if you could provide some insights for the issue. :)

**Comment by baranowb** [comment]
@sudeshnas93 Hey, I think moulali was looking into this. Check with him, though he did not take over this ticket.

**Comment by moulalis** [comment]
Looking into it, I am not able to assign it to myself.

**Comment by moulalis** [comment]
@baranowb Could you please let me know how I can reproduce it so that I can better fix and test it? can it be after TCK runs?

**Comment by baranowb** [comment]
@moulalis WDYM? Its everpresent, just remove .m2 and force maven to download.

**Comment by baranowb** [comment]
though I think this might have been fixed already.

**Comment by baranowb** [comment]
Nope, it wasnt.

**Comment by baranowb** [comment]
https://github.com/jboss-set/cryo/pull/27
